import { ConditionType, TriggerType, EntryType } from '../types/automation.types'
import { DeviceType, Icon } from '../types/device.types'

export const keyType = Symbol('type')

const allOptions = {
  all: {
    [keyType]: 'string',
  },
  dimmable: {
    [keyType]: 'string',
  },
  controllable: {
    [keyType]: 'string',
  },
  rooms: {
    [keyType]: 'string',
  },
  mode: {
    0: 'Dark',
    1: 'Light',
    [keyType]: 'number',
  },
  numbers: {
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    [keyType]: 'number',
  },
  brightness: {
    10: '10%',
    20: '20%',
    30: '30%',
    40: '40%',
    50: '50%',
    60: '60%',
    70: '70%',
    80: '80%',
    90: '90%',
    100: '100%',
    [keyType]: 'number',
  },
  conditions: {
    [ConditionType.State]: 'Device',
    [ConditionType.Range]: 'Time',
    [keyType]: 'number',
  },
  trigger: {
    [TriggerType.Device]: 'Device',
    [TriggerType.Time]: 'Time',
    [TriggerType.Sunrise]: 'Sunrise',
    [TriggerType.Sunset]: 'Sunset',
    [keyType]: 'number',
  },
  entry: {
    [EntryType.Device]: 'Device',
    [EntryType.Wait]: 'Wait',
    [EntryType.If]: 'If',
    [EntryType.IfElse]: 'If Else',
    [EntryType.While]: 'While',
    [keyType]: 'number',
  },
  type: {
    [DeviceType.Button]: 'Button',
    [DeviceType.Dimmer]: 'Dimmer',
    [DeviceType.Door]: 'Door',
    [DeviceType.Garage]: 'Garage',
    [DeviceType.MultiOutlet]: 'Multi-Outlet',
    [DeviceType.Outlet]: 'Outlet',
    [DeviceType.Sensor]: 'Sensor',
    [DeviceType.Switch]: 'Switch',
    [keyType]: 'number',
  },
  icons: {
    [Icon.Camera]: 'Camera',
    [Icon.Button]: 'Button',
    [Icon.ChristmasTree]: 'Christmas Tree',
    [Icon.ChristmasLights]: 'Christmas Lights',
    [Icon.CeilingLight]: 'Ceiling Light',
    [Icon.Door]: 'Door',
    [Icon.Fan]: 'Fan',
    [Icon.Garage]: 'Garage',
    [Icon.LargeLamp]: 'Large Lamp',
    [Icon.Lightbulb]: 'Lightbulb',
    [Icon.Outlet]: 'Outlet',
    [Icon.Sensor]: 'Sensor',
    [Icon.SmallLamp]: 'Small Lamp',
    [Icon.Speakers]: 'Speakers',
    [Icon.Switch]: 'Switch',
    [keyType]: 'number',
  },
}

const test = {
  all: [],
  dimmable: [],
  controllable: [],
  rooms: [],
  mode: [
    [0, 'Dark'],
    [1, 'Light'],
  ],
  numbers: [
    [1, '1'],
    [2, '2'],
    [3, '3'],
    [4, '4'],
    [5, '5'],
  ],
  brightness: [
    [10, '10%'],
    [20, '20%'],
    [30, '30%'],
    [40, '40%'],
    [50, '50%'],
    [60, '60%'],
    [70, '70%'],
    [80, '80%'],
    [90, '90%'],
    [100, '100%'],
  ],
  conditions: [
    [[ConditionType.State], 'Device'],
    [[ConditionType.Range], 'Time'],
  ],
  trigger: [
    [[TriggerType.Device], 'Device'],
    [[TriggerType.Time], 'Time'],
    [[TriggerType.Sunrise], 'Sunrise'],
    [[TriggerType.Sunset], 'Sunset'],
  ],
  entry: [
    [[EntryType.Device], 'Device'],
    [[EntryType.Wait], 'Wait'],
    [[EntryType.If], 'If'],
    [[EntryType.IfElse], 'If Else'],
    [[EntryType.While], 'While'],
  ],
  type: [
    [[DeviceType.Button], 'Button'],
    [[DeviceType.Dimmer], 'Dimmer'],
    [[DeviceType.Door], 'Door'],
    [[DeviceType.Garage], 'Garage'],
    [[DeviceType.MultiOutlet], 'Multi-Outlet'],
    [[DeviceType.Outlet], 'Outlet'],
    [[DeviceType.Sensor], 'Sensor'],
    [[DeviceType.Switch], 'Switch'],
  ],
  icons: [
    [[Icon.Camera], 'Camera'],
    [[Icon.Button], 'Button'],
    [[Icon.ChristmasTree], 'Christmas Tree'],
    [[Icon.ChristmasLights], 'Christmas Lights'],
    [[Icon.CeilingLight], 'Ceiling Light'],
    [[Icon.Door], 'Door'],
    [[Icon.Fan], 'Fan'],
    [[Icon.Garage], 'Garage'],
    [[Icon.LargeLamp], 'Large Lamp'],
    [[Icon.Lightbulb], 'Lightbulb'],
    [[Icon.Outlet], 'Outlet'],
    [[Icon.Sensor], 'Sensor'],
    [[Icon.SmallLamp], 'Small Lamp'],
    [[Icon.Speakers], 'Speakers'],
    [[Icon.Switch], 'Switch'],
  ],
}

